/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "about": "关于",
    "Bobber:": "浮子：",
    "Cages:": "笼子：",
    "Cast out line": "抛线",
    "Crustaceans:": "甲壳类动物：",
    "Deep Sea": "深海",
    "Fly Tackle:": "飞蝇钓具：",
    "Forage for worms": "蠕虫饵料",
    "github": "github",
    "Ground Fish:": "底层鱼：",
    "Guppies:": "孔雀鱼：",
    "Harpoon:": "鱼叉：",
    "Insects:": "昆虫：",
    "Lake": "湖泊",
    "lights off": "关灯",
    "Minnows:": "小鱼：",
    "Money: $": "金钱：$",
    "Mussels:": "贻贝：",
    "Pier": "码头",
    "Reef": "暗礁",
    "Reel in line": "卷线",
    "River": "河流",
    "Shop": "商店",
    "Spear Fishing": "鱼叉捕鱼",
    "Spinner Lure:": "旋转诱饵：",
    "Spoon Lure:": "勺子诱饵：",
    "Squid:": "乌贼：",
    "support me": "支持我",
    "Worms:": "蠕虫：",
    "Auto save every:": "自动保存每：",
    "Bass:": "鲈鱼：",
    "Bass: nothing special but it will sell": "鲈鱼：没什么特别的，可以出售",
    "Close": "关闭",
    "Color theme:": "颜色主题：",
    "Current version: dev-0.2": "当前版本：dev-0.2",
    "dark": "深色",
    "Dev tools:": "开发工具：",
    "disable": "禁用",
    "download save": "下载存档",
    "enable": "启用",
    "five minutes": "5分钟",
    "light": "浅色",
    "lights on": "开灯",
    "Minnows: these would make excellent bait for larger fish": "鲦鱼：这些会成为大鱼的绝佳诱饵",
    "reeling in your line is always full of tedium": "缠着你的线总是充满乏味",
    "restart game": "重新开始游戏",
    "Saves:": "保存：",
    "ten minutes": "10分钟",
    "three minutes": "3分钟",
    "upload save": "上传存档",
    "Worms: writhing around in the mud, these would make good bait": "蠕虫：在泥里扭来扭去，这些都是好诱饵",
    "you cast out your line as far as your arm permits": "你把你的线扔到你的手臂允许的范围内",
    "Chub:": "鲢鱼：",
    "Chub: a large fish, looks to have been a fighter": "鲢鱼：一条大鱼，看起来像个斗士",
    "Nothing for sale!": "没有可供出售的物品！",
    "Sturgeon:": "鲟鱼：",
    "Sturgeon: this one thrashed wildly before submitting to the line": "鲟鱼：这一条在投降之前猛烈挣扎",
    "Anchor": "船锚",
    "Barracuda:": "梭鱼：",
    "Black Drum:": "多须石首鱼：",
    "Business": "商业",
    "Cabin": "船舱",
    "Crabs:": "螃蟹：",
    "Crawdads:": "小龙虾：",
    "Engine": "引擎",
    "Fuel:": "汽油：",
    "Grouper:": "石斑鱼：",
    "Hogfish:": "猪鱼：",
    "Hull": "船体",
    "It's time to take your business to the next level: create your dream enterprise": "是时候让您的业务更上一层楼了：创建您的梦想企业",
    "Lemon Shark:": "柠檬鲨：",
    "Lingcod:": "灵鳕鱼：",
    "Lobster:": "龙虾：",
    "Mackerel:": "鲭鱼：",
    "Mako Shark:": "灰鲭鲨：",
    "Marlin:": "马林鱼：",
    "Moray Eel:": "海鳗：",
    "Opportunities and Morality": "机遇与道德",
    "Pike:": "梭子鱼：",
    "Redfish:": "红鱼：",
    "Salmon:": "三文鱼：",
    "Snapper:": "鲷鱼：",
    "Stonefish:": "石鱼：",
    "Sweden plans to remove newspapers, could they be hiding something?": "瑞典计划删除报纸，他们会隐瞒什么吗？",
    "Swordfish:": "旗鱼：",
    "Tarpon:": "海鲢：",
    "The Next Level": "下一级",
    "The US eliminates sunglasses, war may be on the horizon.": "美国淘汰太阳镜，战争可能即将来临。",
    "Thresher Shark:": "长尾鲨：",
    "Tiger Shark:": "虎鲨：",
    "Total fish caught:": "捕获的鱼总量：",
    "Trout:": "鳟鱼：",
    "Tuna:": "金枪鱼：",
    "Whitefish:": "白鲑：",
    "Workers:": "工人：",
    "Argentina de-materializes ranch dressing, more at 11.": "阿根廷在 11 岁时取消了牧场调味料。",
    "Give business insights": "提供商业见解",
    "Management and Investments": "管理与投资",
    "Offer significant money": "提供大量资金",
    "Video Game Avenues": "电子游戏大道",
    "While you don't know much about video games, your marketing background is considerable.": "虽然您对电子游戏了解不多，但您的营销背景相当可观。",
    "You truly believe in Justin and his ideas. You want to have your name right along him.": "你真的相信贾斯汀和他的想法。 你想在他身边留下你的名字。",
    "After a routine internal audit, it comes to your attention that an accountant has been skimming money from your business.": "在进行例行内部审计后，您会注意到一名会计师一直在从您的业务中窃取资金。",
    "Call your lawyer": "打电话给你的律师",
    "Everyone can be reasoned with, even those caught in the act.": "每个人都可以讲道理，即使是那些被卷入其中的人。",
    "Italy cuts off the internet, you won't believe what happens next!": "意大利断网，你不会相信接下来会发生什么！",
    "Talk with him": "与他交谈",
    "The Book Thief": "偷书贼",
    "This behavior is unaceptable and you wish to make that clear.": "这种行为是不可接受的，您希望明确这一点。",
    "A trusted employee, Pierre, storms into your office demanding his co-worker be fired after he was slapped.": "一位值得信赖的员工皮埃尔冲进你的办公室，要求他的同事在被扇耳光后被解雇。",
    "Egypt abolishes colonization of the Moon, scientists agree.": "科学家们同意，埃及废除了对月球的殖民化。",
    "Fire them both": "解雇他们俩",
    "Pay him off": "还他钱",
    "Workplace Misconduct": "工作场所不当行为",
    "You and him co-worker go way back. This needs to go away.": "你和他的同事回去了。 这需要消失。",
    "You don't need this drama in your workplace. It's best to get rid of them both and let them work it out.": "你的工作场所不需要这种戏剧。 最好把他们俩都干掉，让他们解决。",
    "A trusted employee, Grant, storms into your office demanding his co-worker be fired after he was slapped.": "一位值得信赖的员工格兰特冲进你的办公室，要求他的同事在被扇耳光后被解雇。",
    "Click here to restart the game.": "点击这里重新开始游戏。",
    "Congratulations you've reached the end of the game -- for now!": "恭喜你已经到了游戏的终点——现在！",
    "follow my Twitter": "关注我的推特",
    "for releases, donate via": "对于发布，通过捐赠",
    "Goodbye": "再见",
    "Guatemala re-invents towels, thousands are injured.": "危地马拉重新发明毛巾，数千人受伤。",
    "I hope you enjoyed your time and continue playing! <>< <>< <><": "我希望你喜欢你的时间并继续玩！ <>< <>< <><",
    "Ignore him": "忽略他",
    "Make your stance on theft clear to Bridget.": "向布里奇特表明你对盗窃的立场。",
    "or support me and get frequent updates and changelogs with": "或支持我并获得频繁的更新和变更日志",
    "Patreon": "帕特伦",
    "Paypal": "贝宝",
    "Qatar terminates paperclip factories, you won't believe what happens next!": "卡塔尔终止了回形针工厂，你不会相信接下来会发生什么！",
    "Question her allegations": "质疑她的指控",
    "Severe punishment": "重罚",
    "Some time off without pay and a demotion will right the wrong.": "一段时间无薪休假和降职将是错误的。",
    "South Africa abolishes the internet, the government may shut down.": "南非废除互联网，政府可能会关闭。",
    "Sweden starts revitalization of pigeons, millions attempt to flee the country.": "瑞典开始振兴鸽子，数百万人试图逃离该国。",
    "Verbally threaten": "口头威胁",
    "You can": "你可以",
    "You don't believe him. Nothing like that could happen in a busy workplace.": "你不相信他。在繁忙的工作场所不会发生这样的事情。",
    "You've known who he is talking about for many years. Something doesn't add up.": "你已经知道他在说谁很多年了。有些东西没有加起来。",
    "Peru has banned candycanes, you won't believe what happens next!": "秘鲁已经禁止糖果，你不会相信接下来会发生什么！",
    "South Africa moderates onion rings, civil unrest grows.": "南非缓和洋葱圈，内乱加剧。",
    "China cancels colonization of the Moon, more at 11.": "美国取消对月球的殖民统治，11时取消更多。",
    "Poland raises concerns about breadsticks, thousands are injured.": "波兰对面包架表示担忧，数千人受伤。",
    "Accept without pay": "无偿接受",
    "Ask for proof": "求证据",
    "Berate him for bringing his situation to you instead of working.": "责备他把他的处境带给你而不是工作。",
    "China de-materializes barbecue sauce, this story will shake you!": "中国让烧烤酱去物质化，这个故事震撼你！",
    "Commercial Espionage": "商业间谍",
    "Express your interest": "表达你的兴趣",
    "Fire her": "解雇她",
    "France cuts off iron helmets, lawsuits continue to pile up.": "法国切断铁盔，诉讼不断堆积。",
    "Guatemala cancels shark meat, more at 11.": "危地马拉取消鲨鱼肉，11 日更多。",
    "Housing Crisis": "房地产危机",
    "Ignore her": "无视她",
    "Insult him": "侮辱他",
    "Iran starts revitalization of shark meat, chaos ensues.": "伊朗开始振兴鲨鱼肉，混乱接踵而至。",
    "Its not often people are interested in your business. Why not give her something to remember?": "人们并不经常对您的业务感兴趣。为什么不给她一些值得纪念的东西呢？",
    "Malaysia re-invents hats, civil unrest grows.": "马来西亚重新发明帽子，内乱加剧。",
    "Offer a tour": "提供游览",
    "Offer considerable help": "提供相当大的帮助",
    "Offer light funding": "提供少量资金",
    "One of your workers, Elliot, needs money for temporary housing after his home burned down.": "您的一位工人埃利奥特（Elliot）在房屋被烧毁后需要钱来临时住所。",
    "Qatar considers getting rid of peacocks, experts are perplexed.": "卡塔尔考虑除掉孔雀，专家困惑。",
    "Report him to the police": "向警察报告他",
    "Sweden says its citizens enjoy umbrellas, could they be hiding something?": "瑞典说它的公民喜欢雨伞，他们会隐瞒什么吗？",
    "The Solomon Islands reportedly loves barbecue sauce, hundreds may die.": "据报道，所罗门群岛喜欢烧烤酱，数百人可能会死。",
    "These kinds of people deserve justice. It could happen to any company, including yours.": "这样的人理应得到正义。这可能发生在任何公司，包括你的公司。",
    "Thieves have no place in your business.": "小偷在您的业务中没有地位。",
    "This man is clearly capable financially however you'd like to show your support.": "这个人显然有经济能力，但你想表达你的支持。",
    "This woman is clearly capable financially however you'd like to show your support.": "这个女人显然有经济能力，但你想表达你的支持。",
    "You can hear what he has to say without giving anything up.": "你可以在不放弃任何东西的情况下听到他要说的话。",
    "You can't be firing people on a whim without any proof.": "你不能在没有任何证据的情况下一时兴起解雇人。",
    "You don't believe her. Nothing like that could happen in a busy workplace.": "你不相信她。在繁忙的工作场所不会发生这样的事情。",
    "You don't know much about video games but she seems enthusiastic.": "你对电子游戏了解不多，但她似乎很热情。",
    "You look out for family, and your employees are the closest thing you've got.": "你照顾家人，你的员工是你最亲近的东西。",
    "You truly believe in Simon and his ideas. You want to have your name right along him.": "你真的相信西蒙和他的想法。你想在他身边留下你的名字。",
    "Australia moderates paper, in the face of a high chance of rain.": "面对极有可能下雨的情况，澳大利亚对纸张进行了缓和。",
    "Decline the offer": "拒绝报价",
    "Japan re-invents toilet paper, we were left speechless!": "日本重新发明卫生纸，我们都无语了！",
    "Nico has no right to be using your business and intellectual property in his game without your permission.": "未经您的许可，Nico 无权在他的游戏中使用您的业务和知识产权。",
    "Pay her off": "还她钱",
    "Poland starts debates about the internet, you won't believe what happens next!": "波兰开始讨论互联网，你不会相信接下来会发生什么！",
    "Send a takedown notice": "发送删除通知",
    "Singapore starts revitalization of ice water, riots begin to break out.": "新加坡开始振兴冰水，骚乱开始爆发。",
    "Spain says its citizens enjoy ranch dressing, lawsuits continue to pile up.": "西班牙表示其公民喜欢牧场调味品，诉讼继续堆积。",
    "You and her co-worker go way back. This needs to go away.": "你和她的同事回去了。这需要消失。",
    "You don't know much about video games but he seems enthusiastic.": "你对电子游戏了解不多，但他似乎很热情。",
    "You run a legitimate and moral establishment and want nothing to do with this man.": "你经营着一个合法和道德的机构，不想和这个人有任何关系。",
    "You've known who she is talking about for many years. Something doesn't add up.": "你已经知道她在说谁很多年了。有些东西没有加起来。",
    "Fire him": "解雇他",
    "Ignore it": "忽略它",
    "Report her to the police": "向警方报告她",
    "You run a legitimate and moral establishment and want nothing to do with this woman.": "你经营着一个合法的道德机构，不想与这个女人有任何关系。",
    "Berate her for bringing her situation to you instead of working.": "责备她把她的情况带给你而不是工作。",
    "Continue": "继续",
    "Insult her": "侮辱她",
    "Japan re-invents dark rooms, hundreds may die.": "日本重新发明暗室，数百人可能死亡。",
    "Walk away": "走开",
    "You can't be bothered by other's misfortune.": "你不能被别人的不幸所困扰。",
    "Make your stance on theft clear to Paige.": "",
    "Promote her": "宣传她",
    "Quietly promote her to a suitable position.": "悄悄地把她提拔到合适的位置。",
    "South Korea says its citizens enjoy vapes, we were left speechless!": "韩国说它的公民喜欢电子烟，我们无言以对！",
    "Offer some advice": "提供一些建议",
    "Talk with her": "和她谈谈",
    "Scold him": "骂他一顿",
    "The Philippines considers getting rid of cats, will civilization survive?": "菲律宾考虑除掉猫，文明会继续存在吗？",
    "What he proposes is highly illegal, it's about time someone told him.": "他的提议是高度非法的，是时候有人告诉他了。",
    "Apologize": "道歉",
    "Say you're sorry, but your financials aren't secure enough to help out.": "说你很抱歉，但你的财务状况不够安全，无法提供帮助。",
    "Verbal warning": "口头警告",
    "The amount of money taken was insignificant to your operations.": "拿走的钱对你的业务来说是微不足道的。",
    "A small donation": "一笔小捐赠",
    "Sympathize with her situation and give her a small sum of money.": "同情她的处境，给她一小笔钱。",
    "Israel synthesizes dark rooms, could they be hiding something?": "以色列合成暗室，他们会隐藏什么吗？",
    "Lebanon moderates shark meat, riots begin to break out.": "黎巴嫩缓和鲨鱼肉，骚乱开始爆发。",
    "Scold her": "骂她一顿",
    "What she proposes is highly illegal, it's about time someone told her.": "她的提议是非常非法的，是时候有人告诉她了。",
    "Poland eliminates towels, thousands are injured.": "波兰淘汰毛巾，数千人受伤。",
    "Its not often people are interested in your business. Why not give him something to remember?": "人们很少对你的生意感兴趣。为什么不给他点记忆呢？",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Fast ticks": "快速Tick",
    "Max bait": "最大诱饵",
    "Max fuel": "最大燃料",
    "Max tackle": "最大钓具",
    "Max workers": "最大工人",
    "Money +5000": "金钱+5000",
    "News": "新闻",
    "Non News": "无新闻",
    "Regular ticks": "常规Tick",
    "Unlock business": "解锁商业",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "t": "t",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "设置",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Sell fish (": "出售鱼 (",
    "Fly Fishing permit (": "飞蝇钓许可证 (",
    "Denmark received excess cargo containing": "丹麦收到的超额货物含有 ",
    "Morality: ": "道德：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^\/([\d\.,]+)$/,
    /^\(\$([\d\.,]+)\)$/,
    /^\(\+([\d\.,]+)\)$/,
    /^\(\-([\d\.,]+)\)$/,
    /^\$([\d\.,]+)\)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^After listening to your advice, (.+) is inspired to turn her situation around. \(\+(.+) morality\)$/, '在听取了你的建议后，$1 受到鼓舞，改变了她的处境。（\+$2 道德）'],
    [/^(.+) cancels napkins, and the results are spectacular!$/, '$1 取消餐巾纸，结果是惊人的！'],
    [/^(.+) is thrilled by your offer and spends a day with your employees viewing the various on-goings of your operations. \(\+(.+) morality\)$/, '$1 对您的提议感到非常兴奋，并与您的员工一起度过一天，查看您的各种运营情况。 （\+$2 道德）'],
    [/^(.+) halts imports of \"Deep Sea\" fish. No profits will be gained from these fish for (.+) days.$/, '$1 停止进口 “深海” 鱼。 $2 天内不会从这些鱼中获得任何利润。'],
    [/^(.+) considers the morals of harvesting \"River\" fish. No profits will be gained from these fish for (.+) days.$/, '$1 认为收获 “河流” 鱼是不道德的。 $2 天内不会从这些鱼中获得任何利润。'],
    [/^(.+) considers the morals of harvesting \"Reef\" fish. No profits will be gained from these fish for (.+) days.$/, '$1 认为收获 “暗礁” 鱼是不道德的。 $2 天内不会从这些鱼中获得任何利润。'],
    [/^(.+) cancels shipment of \"Deep Sea\" fish. No profits will be gained from these fish for (.+) days.$/, '$1 取消 “深海” 鱼的运输。 $2 天内不会从这些鱼中获得任何利润。'],
    [/^(.+) cancels shipment of \"River\" fish. No profits will be gained from these fish for (.+) days.$/, '$1 取消 “河流” 鱼的运输。 $2 天内不会从这些鱼中获得任何利润。'],
    [/^(.+) found counterfeit \"Spear Fishing\" fish. No profits will be gained from these fish for (.+) days.$/, '$1 发现假冒 “鱼叉捕鱼” 鱼。 $2 天内不会从这些鱼中获得任何利润。'],
    [/^(.+) discovered disease in \"Pier\" fish. No profits will be gained from these fish for (.+) days.$/, '$1 在“码头”鱼身上发现了疾病。 $2 天内不会从这些鱼中获得任何利润。'],
    [/^(.+) does not want to overfish \"Reef\" fish. No profits will be gained from these fish for (.+) days.$/, '$1 不想过度捕捞 “暗礁” 鱼。 $2 天内不会从这些鱼中获得任何利润。'],
    [/^(.+) received excess cargo containing \"Lake\" fish. No profits will be gained from these fish for (.+) days.$/, '$1 收到的超额货物包含 “湖泊” 鱼。 $2 天内不会从这些鱼中获得任何利润。'],
    [/^(.+) received excess cargo containing \"Pier\" fish. No profits will be gained from these fish for (.+) days.$/, '$1 收到的超额货物包含 “码头” 鱼。 $2 天内不会从这些鱼中获得任何利润。'],
    [/^(.+) discovered disease in \"River\" fish. No profits will be gained from these fish for (.+) days.$/, '$1 在“河流”鱼身上发现了疾病。 $2 天内不会从这些鱼中获得任何利润。'],
    [/^(.+) encountered a budget issue regarding \"Deep Sea\" fish. No profits will be gained from these fish for (.+) days.$/, '$1 遇到了有关“深海”鱼类的预算问题。 $2 天内不会从这些鱼中获得任何利润。'],
    [/^Unfortunately no witnesses or camera feed can be found. (.+) does not wish to pursue it any further when you suggest invloving the police. \(\+(.+) morality\)$/, '不幸的是，找不到目击者或摄像头。 当你建议警方介入时，$1 不想再追究了。 （\+$2 道德）'],
    [/^(.+) appreciates your interest and you spend a few hours talking over various subjects.  \(No morality change\)$/, '$1 感谢您的兴趣，您花了几个小时谈论各种主题。 （没有道德改变）'],
    [/^You turn your back and walk away. (.+) sighs in defeat and tries his co-workers. \(\-(.+) morality\)$/, '你转身就走。 $1 失败地叹了口气，并尝试了他的同事。 （\-$2 道德）'],
    [/^You sit down with (.+) and talk the situation out. (.+) says he's been going through a hard time but will return the money. \((.+)\) \(\+(.+) morality\)$/, '你和 $1 坐下来谈谈情况。 $2 说他经历了一段艰难时期，但会退还这笔钱。 （$3）（\+$4 道德）'],
    [/^(.+) gives you a quick hug followed by a genuine thanks. \(\+(.+) morality\)$/, '$1 给了你一个快速的拥抱，然后是真诚的感谢。 （\+$2 道德）'],
    [/^(.+) has no right to be using your business and intellectual property in her game without your permission.$/, '未经您的许可，$1 无权在她的游戏中使用您的业务和知识产权。'],
    [/^(.+) at your non-action, Piper decides it's time to lawyer up. Fortunately for you she quit and therefore cannot pursure charges against you. \(\-(.+) morality\)$/, '$1 对你的不作为感到震惊，决定是时候找律师了。 对你来说幸运的是，她辞职了，因此无法对你提出指控。 （\-$2 道德）'],
    [/^You say you'll take everything: her job, her house, even her dog. (.+) cleans up her act immediately. \(\-(.+) morality\)$/, '你说你会拿走一切：她的工作，她的房子，甚至她的狗。 $1 立即清理了她的行为。 （\-$2 道德）'],
    [/^After a few days, police arrest (.+) and charges are soon filed against her. \(\+(.+) morality\)$/, '几天后，警方逮捕了 $1，并很快对她提出指控。 （\+$2 道德）'],
    [/^You discuss the issue with (.+) and the co-worker in question it appears to have been a misunderstanding between the two. After a mutual apology they go back to work.  \(No morality change\)$/, '您与 $1 和有问题的同事讨论这个问题，这似乎是两人之间的误解。 在相互道歉后，他们又回去工作了。 （没有道德改变）'],
    [/^Make your stance on theft clear to (.+).$/, '向 $1 表明你对盗窃的立场。'],
    [/^One of your workers, (.+), needs money for temporary housing after her home burned down.$/, '你的一个工人，$1，在她的房子被烧毁后，需要钱来买临时住房。'],
    [/^One of your workers, (.+), needs money for temporary housing after his home burned down.$/, '你的一个工人，$1，在他的房子被烧毁后，需要钱来买临时住房。'],
    [/^You call (.+) into your office. You tell him that you cannot allow him to continue working with you.  \(No morality change\)$/, '你把 $1 叫到你的办公室。 你告诉他你不能让他继续和你一起工作。 （没有道德改变）'],
    [/^(.+) starts debates about artificial intelligence, in the face of a high chance of rain.$/, '$1 面临下雨的可能性很高，因此开始了关于人工智能的辩论。'],
    [/^(.+) has banned dark rooms, thousands are injured.$/, '$1 已取缔暗室，数千人受伤。'],
    [/^(.+) knows about the audit. No need to press further.$/, '$1 了解审计情况。无需进一步按压。'],
    [/^(.+) is a former manager at your biggest competitor. For the right price, he can reveal their business plans.$/, '$1 是你最大竞争对手的前任经理。以合适的价格，他可以透露他们的商业计划。'],
    [/^(.+) is a former manager at your biggest competitor. For the right price, she can reveal their business plans.$/, '$1 是你最大竞争对手的前任经理。以合适的价格，她可以透露他们的商业计划。'],
    [/^A trusted employee, (.+), storms into your office demanding her co-worker be fired after she was slapped.$/, '一位值得信赖的员工 $1 冲进你的办公室，要求在她被扇耳光后解雇她的同事。'],
    [/^A trusted employee, (.+), storms into your office demanding his co-worker be fired after she was slapped.$/, '一位值得信赖的员工 $1 冲进你的办公室，要求在他被扇耳光后解雇她的同事。'],
    [/^A software developer, (.+), is inspired by your business's success and he has some grand plans for an online fishing game.$/, '软件开发人员 $1 受到您企业成功的启发，他对在线钓鱼游戏制定了一些宏伟计划。'],
    [/^A software developer, (.+), is inspired by your business's success and she has some grand plans for an online fishing game.$/, '软件开发人员 $1 受到您企业成功的启发，她对在线钓鱼游戏制定了一些宏伟计划。'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);